export const materias = [
  // ------------ OBLIGATORIAS ------------
  { semestre: 1, nombre: "Conceptos contables", creditos: 10, area: "Contabilidad e impuestos", requisitos: [] },
  { semestre: 1, nombre: "Administración y Gestión de las organizaciones 1", creditos: 10, area: "Administración", requisitos: [] },
  { semestre: 1, nombre: "Introducción a la microeconomía", creditos: 10, area: "Economía", requisitos: [] },
  { semestre: 1, nombre: "Calculo 1", creditos: 10, area: "Métodos cuantitativos", requisitos: [] },
  { semestre: 2, nombre: "Contabilidad General 1", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Conceptos contables"] },
  { semestre: 2, nombre: "Derecho Civil", creditos: 10, area: "Jurídica", requisitos: [] },
  { semestre: 2, nombre: "Economía descriptiva", creditos: 10, area: "Economía", requisitos: [] },
  { semestre: 3, nombre: "Introducción a la estadística", creditos: 10, area: "Economía", requisitos: ["Calculo 1"] },
  { semestre: 3, nombre: "Contabilidad General 2", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Contabilidad General 1"] },
  { semestre: 3, nombre: "Derecho Comercial", creditos: 10, area: "Jurídica", requisitos: ["Derecho Civil"] },
  { semestre: 3, nombre: "Procesos y Sistemas de información", creditos: 10, area: "Administración", requisitos: ["Administración y Gestión de las organizaciones 1"] },
  { semestre: 4, nombre: "Contabilidad General 3", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Contabilidad General 2"] },
  { semestre: 4, nombre: "Matematica financiera", creditos: 10, area: "Métodos cuantitativos", requisitos: ["Calculo 1"] },
  { semestre: 4, nombre: "Legislación laboral y seguridad social", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Conceptos contables", "Derecho Civil"] },
  { semestre: 4, nombre: "Derecho societario", creditos: 10, area: "Jurídica", requisitos: ["Derecho Civil"] },
  { semestre: 5, nombre: "Modelos y sistemas de costos", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Contabilidad General 3"] },
  { semestre: 5, nombre: "Derecho tributario", creditos: 10, area: "Jurídica", requisitos: ["10 créditos en el área jurídica"] },
  { semestre: 5, nombre: "Etica y ejercicio profesional", creditos: 5, area: "Actividades integradoras", requisitos: ["Contabilidad General 2", "Derecho Comercial"] },
  { semestre: 6, nombre: "Contabilidad superior 1", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["50 créditos del área contable."] },
  { semestre: 6, nombre: "Control interno", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Procesos y Sistemas de información", "40 créditos en el área contable."] },
  { semestre: 6, nombre: "Contabilidad Gerencial", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["160 créditos de avance de carrera, incluyendo Modelos y Sistemas de Costos y Matemática Financiera."] },
  { semestre: 6, nombre: "Tributaria 1", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Contabilidad General 3", "Derecho Tributario"] },
  { semestre: 7, nombre: "Auditoría 1", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["160 créditos de avance de carrera que incluyen: Derecho Societario, Legislación Laboral y Seguridad Social, Control Interno y Contabilidad Superior"] },
  { semestre: 7, nombre: "Tributaria 2", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Tributaria 1"] },
  { semestre: 7, nombre: "Finanzas corporativas", creditos: 10, area: "Administración", requisitos: [
    "Administración y Gestión de las Organizaciones 1",
    "Matemática Financiera",
    "Introducción a la Estadística",
    "40 créditos en el Área de Contabilidad e Impuestos",
    "30 créditos en el Área de Economía",
    "180 créditos mínimos de avance en la carrera"
  ] },
  { semestre: 8, nombre: "Informes profesionales de contador público", creditos: 10, area: "Contabilidad e impuestos", requisitos: ["Auditoría 1"] },
  { semestre: 8, nombre: "Práctica pericial en el ámbito Judicial", creditos: 5, area: "Actividades integradoras", requisitos: [
    "Contabilidad Superior",
    "Derecho Comercial",
    "Derecho Societario",
    "Ética y Ejercicio Profesional"
  ] },
  { semestre: 8, nombre: "Gestión financiera del estado", creditos: 10, area: "Administración", requisitos: [
    "30 créditos del área contable",
    "20 créditos del área administración",
    "15 créditos del área jurídica",
    "180 créditos de avance de Carrera"
  ] },

  // ------------ OPCIONALES ------------
  { semestre: 2, nombre: "Administración y Gestión de las organizaciones 2", creditos: 10, area: "Administración", requisitos: ["Administración y Gestión de las organizaciones 1"], opcional: true },
  { semestre: 2, nombre: "Ciencia Política", creditos: 10, area: "CIENCIAS SOCIALES Y HUMANÍSTICAS", requisitos: [], opcional: true },
  { semestre: 2, nombre: "Desarrollo y Bienestar", creditos: 10, area: "CIENCIAS SOCIALES Y HUMANÍSTICAS", requisitos: [], opcional: true },
  { semestre: 2, nombre: "Algebra lineal", creditos: 10, area: "Métodos cuantitativos", requisitos: [], opcional: true },
  { semestre: 3, nombre: "Macroeconomía 1", creditos: 10, area: "Economía", requisitos: ["Introducción a la Microeconomía"], opcional: true },
  { semestre: 3, nombre: "Taller de iniciación a la investigación", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["40 créditos de avance"], opcional: true },
  { semestre: 4, nombre: "Economía Circular", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["100 créditos"], opcional: true },
  { semestre: 4, nombre: "Administración de Recursos humanos", creditos: 10, area: "Administración", requisitos: ["Administración y Gestión de las organizaciones 2"], opcional: true },
  { semestre: 4, nombre: "Sistemas de información", creditos: 10, area: "Administración", requisitos: ["Administración y Gestión de las organizaciones 1", "Contabilidad General 1"], opcional: true },
  { semestre: 4, nombre: "sociología de la empresa y Management", creditos: 10, area: "CIENCIAS SOCIALES Y HUMANÍSTICAS", requisitos: ["80 créditos de avance de carrera que incluya Administración y Gestión 1 ó Introducción a la Microeconomía"], opcional: true },
  { semestre: 4, nombre: "sociología contemporánea", creditos: 10, area: "CIENCIAS SOCIALES Y HUMANÍSTICAS", requisitos: [], opcional: true },
  { semestre: 4, nombre: "sociología económica", creditos: 10, area: "CIENCIAS SOCIALES Y HUMANÍSTICAS", requisitos: [], opcional: true },
  { semestre: 5, nombre: "EFI Microcecea", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["Contar con 180 créditos aprobados"], opcional: true },
  { semestre: 5, nombre: "Taller de ética y responsabilidad social", creditos: 5, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["Procesos y sistemas de Información", "Modelos y Sistemas de Costos"], opcional: true },
  { semestre: 5, nombre: "EFI: Cooperativas de trabajo y colectivos autogestionados", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["180 créditos aprobados"], opcional: true },
  { semestre: 5, nombre: "seguros de vida", creditos: 10, area: "Métodos cuantitativos", requisitos: ["Matemática Financiera", "Introducción a la Estadística"], opcional: true },
  { semestre: 5, nombre: "Marketing Básico", creditos: 10, area: "Administración", requisitos: [], opcional: true },
  { semestre: 5, nombre: "Análisis de datos en administración", creditos: 10, area: "Métodos cuantitativos", requisitos: ["Introducción a la Estadística"], opcional: true },
  { semestre: 6, nombre: "Contabilidad de instituciones financieras no bancarias", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Tener aprobados 160 créditos de avance de carrera que incluyan Contabilidad General III y Derecho Comercial"], opcional: true },
  { semestre: 6, nombre: "Derecho Público", creditos: 10, area: "Jurídica", requisitos: [], opcional: true },
  { semestre: 6, nombre: "EFI - Costos para la Gestión de Emprendimientos Sociales y Comunitarios", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["Contabilidad Gerencial."], opcional: true },
  { semestre: 6, nombre: "Marketing Estratégico", creditos: 10, area: "Administración", requisitos: ["Marketing Básico"], opcional: true },
  { semestre: 6, nombre: "Comercio Internacional", creditos: 10, area: "Administración", requisitos: ["15 Créditos Área Jurídica", "Matemática financiera", "Modelo y sistemas de costos"], opcional: true },
  { semestre: 6, nombre: "Introd. al emprendedurismo", creditos: 10, area: "Administración", requisitos: ["240 créditos de avance de Carrera"], opcional: true },
  { semestre: 6, nombre: "Economía y finanzas públicas", creditos: 10, area: "Economía", requisitos: ["Introducción a la Microeconomía", "Economía Descriptiva"], opcional: true },
  { semestre: 6, nombre: "Historia Económica del Uruguay", creditos: 10, area: "CIENCIAS SOCIALES Y HUMANÍSTICAS", requisitos: ["30 creditos en economia", "Historia Economica Mundial"], opcional: true },
  { semestre: 6, nombre: "Métodos Cuantitativos en Decisiones Gerenciales", creditos: 10, area: "Métodos Cuantitativos", requisitos: ["Matemática Financiera", "Introducción a la Estadística", "160 creditos de avance en la carrera"], opcional: true },
  { semestre: 6, nombre: "Derecho Digital", creditos: 10, area: "Jurídica", requisitos: ["150 créditos de avance de carrera que incluyan Derecho Comercial y Derecho Societario."], opcional: true },
  { semestre: 6, nombre: "Modelos de Comportamiento Estratégico", creditos: 10, area: "Métodos Cuantitativos", requisitos: ["Introducción a la Estadística"], opcional: true },
  { semestre: 7, nombre: "Contabilidad Bancaria", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["50 Créditos del Área Contable"], opcional: true },
  { semestre: 7, nombre: "Práctica Profesional Inicial", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["100 créditos del Área Contable", "Tributaria 1"], opcional: true },
  { semestre: 7, nombre: "EFI - Emprendimientos productivos en contexto de encierro", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["180 créditos aprobados"], opcional: true },
  { semestre: 7, nombre: "Contabilidad Superior 2", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Contabilidad Superior 1"], opcional: true },
  { semestre: 7, nombre: "Marketing de Servicios", creditos: 10, area: "Administración", requisitos: ["Marketing Estratégico"], opcional: true },
  { semestre: 7, nombre: "Marketing Digital", creditos: 10, area: "Administración", requisitos: ["Marketing Estratégico"], opcional: true },
  { semestre: 7, nombre: "Comportamiento Organizacional", creditos: 10, area: "Administración", requisitos: ["170 créditos de avance"], opcional: true },
  { semestre: 7, nombre: "Contabilidad Social y Ambiental", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Contabilidad Gerencial"], opcional: true },
  { semestre: 7, nombre: "Contabilidad Gerencial Avanzada", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Contabilidad Gerencial"], opcional: true },
  { semestre: 7, nombre: "Blockchain y Contabilidad", creditos: 5, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["180 créditos totales, incluyendo 60 créditos de contabilidad e impuestos."], opcional: true },
  { semestre: 7, nombre: "Modelización y Automatización Robótica de Procesos", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["180 créditos totales, incluyendo 60 créditos de contabilidad e impuestos."], opcional: true },
  { semestre: 8, nombre: "Contabilidades Especiales", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["270 créditos de avance en la carrera que incluya: Contabilidad Superior I y Auditoría I"], opcional: true },
  { semestre: 8, nombre: "Costos y Gestión de Actividades", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Contabilidad Gerencial o Costo para la toma de decisiones"], opcional: true },
  { semestre: 8, nombre: "Tributaria III", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Derecho Tributario", "Tributaria I", "Tributaria II"], opcional: true },
  { semestre: 8, nombre: "Auditoría Interna", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Control Interno", "Auditoría I"], opcional: true },
  { semestre: 8, nombre: "Logística y Cadena de Suministros", creditos: 10, area: "Contabilidad e Impuestos", requisitos: ["Contabilidad Gerencial"], opcional: true },
  { semestre: 8, nombre: "Contabilidad en Sistemas Integrados de Gestión (SIG/ERP)", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["180 créditos totales, incluyendo 60 créditos de contabilidad e impuestos."], opcional: true },
  { semestre: 8, nombre: "Información Analítica para la Gestión", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: ["180 créditos totales, incluyendo 60 créditos de contabilidad e impuestos."], opcional: true },
  { semestre: 8, nombre: "EFI: CCEEmprende", creditos: 10, area: "ACTIVIDADES INTEGRADORAS", requisitos: [
    "Administración y Gestión de las Organizaciones I",
    "Matemática Financiera",
    "Introducción a la Estadística",
    "40 créditos en el Área de Contabilidad e Impuestos",
    "30 créditos en el Área de Economía",
    "180 créditos mínimos de avance"
  ], opcional: true },
  { semestre: 8, nombre: "Mercados Financieros", creditos: 10, area: "Administración", requisitos: ["Finanzas Corporativas", "270 créditos aprobados"], opcional: true },
  { semestre: 8, nombre: "Proyectos de Inversión", creditos: 10, area: "Administración", requisitos: ["Finanzas Corporativas", "30 créditos en Economía", "270 créditos en el avance de la carrera"], opcional: true },
  { semestre: 8, nombre: "Economía y Gestión de Organizaciones de Salud", creditos: 10, area: "Administración", requisitos: ["Un mínimo de 20 créditos en el Área de Administración.", "Un mínimo de 100 créditos aprobados"], opcional: true },
  { semestre: 8, nombre: "Auditoría de Sistemas de Información", creditos: 10, area: "Contabilidad e Impuestos", requisitos: [], opcional: true }
];
